### ISSUE TITLE
 undefined: fs.RegisterWithNamespace

### ISSUE THREAD

**Issue by semyon-dev** [rakyll/statik#104]
**I am trying to build** (GOOS=linux   GOARCH=amd64 go build app/main.go) but getting this error:
`app/statik/statik.go:12:2: undefined: fs.RegisterWithNamespace` \
\
**code from auto generated statik:**  `fs.RegisterWithNamespace("default", data)`
 
how to resolve this?

**Comment by jcchavezs** [comment]
What version of static are you using?

José Carlos Chávez


tor. 20. feb. 2020 kl. 22:35 skrev Semyon <notifications@github.com>:

**Comment by semyon-dev** [comment]
last version (v0.1.6)

**Comment by semyon-dev** [comment]
Thanks for so fast reply, I just updated go.mod via go get and it's working now:
` go get -u github.com/rakyll/statik@46bd79c4540341fe472fe71dd2ce0ccd4e635450`
