### ISSUE TITLE
Relative path not working

### ISSUE THREAD

**Issue by razonyang** [rakyll/statik#109]
I modified the [example](https://github.com/rakyll/statik/blob/master/example/main.go), relative path seems not working.

Code snippet:

```go
func main() {
	statikFS, err := fs.New()
	...
	for _, name := range []string{"hello.txt", "/hello.txt"} {
		_, err := statikFS.Open(name)
		if err != nil {
			log.Printf("file %s: %s", name, err)
		} else {
			log.Printf("file %s exists", name)
		}
	}
        ...
}
```

```shell
$ go run main.go
2020/03/11 07:50:11 file hello.txt: file does not exist
2020/03/11 07:50:11 file /hello.txt exists
```

**Comment by jcchavezs** [comment]
I think it makes sense we only support absolute path, I can't think of a
use case where we don't use it. Hence one option here is to either prepend
slash when missing or just update the documentation to specify this. Any
thoughts on this @rakyll?

**Comment by razonyang** [comment]
@jcchavezs Thx, I solved it by adding a forward slash.
But, IMO, a file system(`http.FileSystem`) should be able to open relative path files, such as `http.Dir` and `packr.Box`.
