### ISSUE TITLE
please tag and version this project

### ISSUE THREAD

**Issue by aviau** [rakyll/statik#15]
Hello,

Can you please tag and version this project?

I am the Debian Maintainer for statik and versioning would help Debian keep up with development.

**Comment by rakyll** [comment]
Surely, I can create a version tag.

**Comment by rakyll** [comment]
All the releases will be tagged with a semvar version and will have git tag. v0.1.0 has just been pushed. https://github.com/rakyll/statik/tree/v0.1.0

**Comment by aviau** [comment]
Thanks!
