### ISSUE TITLE
use static files  in html templates

### ISSUE THREAD

**Issue by Pechenn** [rakyll/statik#18]
Hi, i use Statik for css and js files and wondering if it possible to use compiled html files in templates. Like `loginfile, _ := statikFS.Open("/tmpl/login.html")`
`tHeader, err := tHeader.ParseFiles(loginfile.data)
`
Thanks.

**Comment by ptman** [comment]
Couldn't you do something like:

    s, err := fs.New()
    f, err := s.Open("/tmpl/login.html")
    b, err := ioutil.ReadAll(f)
    t, err := template.New("login").Parse(string(b))

?

**Comment by Pechenn** [comment]
thanks for respond. now i'm using bindata_fs for that.

**Comment by jcchavezs** [comment]
Closing this issue as it seems @Pechenn sorted this out.
