### ISSUE TITLE
no zip data registered

### ISSUE THREAD

**Issue by mehmetkose** [rakyll/statik#32]
whats wrong with that?

![screen shot 2017-09-17 at 01 49 38](https://user-images.githubusercontent.com/706678/30516530-a5797074-9b4a-11e7-9dc7-46a2c998e504.png)

**Comment by mehmetkose** [comment]
And whats happening here?

![Uploading Screen Shot 2017-09-17 at 02.09.40.png…]()

**Comment by rakyll** [comment]
You are expected to import the generated statik package to register zip data or call https://godoc.org/github.com/rakyll/statik/fs#Register to manually do it. If you are not registering any zip data, it will complain.

What's the use case for importing this package and not registering no data?

**Comment by jcchavezs** [comment]
@mehmetkose you need to import the generated package and the init will do the trick:

`import 	_ "github.com/your/package/route/statik"`

**Comment by chis0m** [comment]
> @mehmetkose you need to import the generated package and the init will do the trick:
> 
> `import _ "github.com/your/package/route/statik"`

Thank you
