### ISSUE TITLE
Possibility to add a package comment

### ISSUE THREAD

**Issue by vdobler** [rakyll/statik#51]
Several tools complain if a package has no package level comment at all,
eg. staticcheck:

    staticcheck ./...
    statik/statik.go:3:1: at least one file in a package should have a package comment (ST1000)

I'd like to propose the addition of a new command line flag with a
useful default, e.g.

    flagPkgCmt     = flag.String("c", "Package statik contains static assets.", "Package comment")

(An empty value for *flagPgkCmt would omit the comment.)

If this sounds sensible I could provide a PR.

**Comment by rakyll** [comment]
Happy to review a PR for this feature!

**Comment by dolmen** [comment]
This has been implemented in #52 and merged. Close?
