### ISSUE TITLE
Readdir should treat zero for count value as it was negative to be fully compatible with the interface

### ISSUE THREAD

**Issue by shakahl** [rakyll/statik#68]
Hi @rakyll 

Thanks for the `statik`, it's a great lib:) 

I found an issue in the `Readdir` implementation while I was using another library that called statik's fs.Readdir(0) and it resulted in a problem. No file was found in this case.

It should treat the zero value and the negatives the same as the GoDoc recommends: https://golang.org/pkg/os/#File.Readdir

The problematic `Readdir` implementation:
https://github.com/rakyll/statik/blob/3bac566d30cdbeddef402a80f3d6305860e59f12/fs/fs.go#L190

I fould the issue when I was using this library: https://github.com/shurcooL/httpfs/issues/8

All best,
@shakahl

**Comment by shakahl** [comment]
Mabe the duplicate of this issue: #58

**Comment by rakyll** [comment]
Happy to review the change if you would like to send one! Otherwise, I can only look at it later this week.

**Comment by dmitshur** [comment]
@shakahl Are you still planning to send a PR? If not, I can do it.

**Comment by dmitshur** [comment]
I'll send a PR since I'm already looking at this, it's a very small change.

**Comment by jcchavezs** [comment]
Go for it :).

man. 8. jul. 2019, 02:45 skrev Dmitri Shuralyov <notifications@github.com>:

**Comment by shakahl** [comment]
@dmitshur Thank you for the PR! :) Unfortunately, I've been a little bit overwhelmed in the last few weeks.

**Comment by dmitshur** [comment]
No problem @shakahl, that's very relatable. Thanks for reporting this issue.
