### ISSUE TITLE
Embedding fs package directly in output

### ISSUE THREAD

**Issue by mjibson** [rakyll/statik#8]
Thoughts on adding the fs package to the output? This would remove the need for the generated package to have non std-lib imports, thus removing the need to vendor the fs package at all. I'd be happy to do the work if you think the design is good.

**Comment by rakyll** [comment]
It sounds like a good idea. If you are still up to it, please open a PR.

(Sorry for the latest reply of all times.)

**Comment by mjibson** [comment]
I wrote my own package to do this instead.
