### ISSUE TITLE
Deterministic file generation 

### ISSUE THREAD

**Issue by nmiculinic** [rakyll/statik#99]
When using statik with default settings, and zipping the data the resulting file is different every time. Is it possible having a deterministic output for each run? 

The goal is committing statik generated files in the VCS, and having them differ each run complicates things. 

A command used is:

```
    statik -src=${src} -p ${component} -dest ${dest} -f -c ''
```

**Comment by antifuchs** [comment]
I ran into this too, and the trick is to pass `-m` - that causes `statik` to not set the file modification date, which can differ across machines; it's not extra explicitly called out in the help text of `statik`, but that's how you get deterministic output!

**Comment by jcchavezs** [comment]
Would you give an update in the docs?
